//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tdirectory) DeepCopyInto(out *Tdirectory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tdirectory.
func (in *Tdirectory) DeepCopy() *Tdirectory {
	if in == nil {
		return nil
	}
	out := new(Tdirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tdirectory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdirectoryApp) DeepCopyInto(out *TdirectoryApp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdirectoryApp.
func (in *TdirectoryApp) DeepCopy() *TdirectoryApp {
	if in == nil {
		return nil
	}
	out := new(TdirectoryApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdirectoryDB) DeepCopyInto(out *TdirectoryDB) {
	*out = *in
	out.DBSize = in.DBSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdirectoryDB.
func (in *TdirectoryDB) DeepCopy() *TdirectoryDB {
	if in == nil {
		return nil
	}
	out := new(TdirectoryDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdirectoryList) DeepCopyInto(out *TdirectoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tdirectory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdirectoryList.
func (in *TdirectoryList) DeepCopy() *TdirectoryList {
	if in == nil {
		return nil
	}
	out := new(TdirectoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TdirectoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdirectorySpec) DeepCopyInto(out *TdirectorySpec) {
	*out = *in
	out.TdirectoryApp = in.TdirectoryApp
	in.TdirectoryDB.DeepCopyInto(&out.TdirectoryDB)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdirectorySpec.
func (in *TdirectorySpec) DeepCopy() *TdirectorySpec {
	if in == nil {
		return nil
	}
	out := new(TdirectorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdirectoryStatus) DeepCopyInto(out *TdirectoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdirectoryStatus.
func (in *TdirectoryStatus) DeepCopy() *TdirectoryStatus {
	if in == nil {
		return nil
	}
	out := new(TdirectoryStatus)
	in.DeepCopyInto(out)
	return out
}
