---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - testoperators.tdirectory.com
  resources:
  - tdirectories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testoperators.tdirectory.com
  resources:
  - tdirectories/finalizers
  verbs:
  - update
- apiGroups:
  - testoperators.tdirectory.com
  resources:
  - tdirectories/status
  verbs:
  - get
  - patch
  - update
