apiVersion: testoperators.tdirectory.com/v1
kind: Tdirectory
metadata:
  labels:
    app.kubernetes.io/name: tdirectory
    app.kubernetes.io/instance: tdirectory-sample
    app.kubernetes.io/part-of: tdirectory-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tdirectory-operator
  name: tdirectory-sample
spec:
  tdirectoryApp:
    Name: "tdirectoryApp"
    repository: "tdirectory"
    tag: v1
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    port: 80
    targetPort: 8080
    serviceType: "LoadBalancer"
  tdirectoryDB:
    Name: "tdirectoryMongo"
    repository: "mongo"
    tag: latest
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    port: 27017
    dbSize: 2Gi
